name: Workflow to test the custom action

on:
  workflow_dispatch:

jobs:

  get_commodity_price:
    runs-on: ubuntu-latest
    steps:
      - name: Get commodity price step
        uses: dmpinero/get-commodity-price-action@v1.0.1
        with:
          commodity: 'silver'